providers = ["...", "python"]

[phases.install]
cmds = [
    "npm install -g corepack@0.24.1 && corepack enable",
    "yarn install --check-cache",
]
dependsOn = ["setup"]

[phases.build]
cache_directories = [
    '**/dist/**',
    '**/prisma/generated/**',
    '**/.next/**',
    '!**./.next/cache/**',
    '**/.tamagui/**',
]
