name: 'Your Workflow Name'

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Railway Deploy
        uses: bervProject/railway-deploy@0.1.2-beta
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "scheduler"